# Site settings
author: Mario
title: Mario’s Blog
header-img: img/home-bg.png
email: dimitropoulosmarios@hotmail.com
copyright_name: Mario
description: > # this means to ignore newlines until "baseurl:"
  My journey in Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MariosDimi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
